# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

import sys
import pyspark.sql.functions as F

sys.path.append("/Workspace/Users/williamfabyan14@gmail.com/LendingPipeline")

# COMMAND ----------

# MAGIC %md
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT * FROM business.lending.silver_fact_loan_activity
# MAGIC

# COMMAND ----------

exp=_sqldf

# COMMAND ----------

display(exp.filter(F.col("")))
